### ISSUE TITLE
Linux/*nix paths

### ISSUE THREAD

**Issue by hakusaro** [DrakiaXYZ/Stargate-Bukkit#10]
You're currently using windows specific directory deliminators (back slashes `\`) instead of the conventional *nix ones. As a result, you have the unintended consequence of having people like myself accidentally removing directories, because they're not in the plugins folder.

```
[shank@aurora shankshock-quantum]$ ls
Backups             help.yml       permissions.yml   server.log.lck     stock_nether
Minecraft_RKit.jar  lib            plugins           server.properties  svcreative
banned-ips.txt      ops.txt        plugins\Stargate  shankshock         toolkit
banned-players.txt  panem          rtoolkit.bat      spigotmc.jar       wepif.yml
bukkit.yml          panem_nether   rtoolkit.sh       start.sh           white-list.txt
bukkit_update       panem_the_end  server.log        stock
```

This is probably because of paths being built with string concatenation instead of using File objects. See [this StackOverflow post for a good solution](http://stackoverflow.com/questions/412380/combine-paths-in-java/412495#412495) to this problem.

**Comment by DrakiaXYZ** [comment]
You are able to change the path in config.yml. This is not behaviour I have encountered on any of my test systems, or servers I have run, all of which are *nix based.

config.yml, and all of my code, has utilized "/" as opposed to "\" for file paths for as long as I can remember. If you can point out where I'm utilizing a windows-specific directory delimiter I would be glad to fix it, until then I am closing this as invalid.

**Comment by hakusaro** [comment]
Hmm, thanks! I didn't know that was configurable in config.yml. Probably a bad FTP client at some point or another.

**Comment by DrakiaXYZ** [comment]
No problem, hopefully it's just a config.yml messup. As I said, I do all my testing in Linux, so no clue why it would be happening to you.
