### ISSUE TITLE
Gate Proximity Issue

### ISSUE THREAD

**Issue by JAG100** [DrakiaXYZ/Stargate-Bukkit#11]
I snapped a picture of a problem I'm having. 

I would really like to be able to locate gates at a 45 degree angle to one another wherein they share a common border with the next gate.  Please see design example picture at the link below:

https://www.dropbox.com/sh/tdqxtvrxghq4ced/CUuK5rfk5S

Presently, Stargates won't allow me to create gates in this particular configuration but I just love this spawn design and really wanted to take advantage of the 45 degree locality of the gates.  Is there any way to solve this problem?  I'd be willing to compensate anyone for their time in helping me solve this one.  :-)

Best,
JAG100

**Comment by DrakiaXYZ** [comment]
The main issue with implementing something like this is Stargate does lookups based on the gate frame blocks, and a block can only be associated with one Portal object (It's a HashMap, for faster lookups). If something like this were allowed it would result in only one gate being linked to the corner blocks, and thus lookups failing to work correctly.

What you could do is design a gate layout that looks like this:

```
   XX
   ..X
   ..-
   *.-
   XX
```

This would of course require the button and sign being on the same side, but if you're using an always-on gate that shouldn't be an issue.

**Comment by JAG100** [comment]
Wow!  That's a great  idea. I'll try this!!

On the subject of gate design, I tried to make the gates wider and taller but couldn't figure out how to. 

Is that possible as well?  I'd love a sample of how to do that!!!

Thank so much.

**Comment by DrakiaXYZ** [comment]
You can make as many .gate files as you want, an explanation of the format is available on the support forums:
http://forum.thedgtl.net/viewtopic.php?f=4&t=5#gat

**Comment by JAG100** [comment]
I guess I'm not the sharpest tool in the shed. I read that link before and tried to widen the gate by adding an extra X or two at the top and bottom. I tried increasing how tall as well to keep proportionality but nothing other than the default seemed to work for me. Could I trouble you to show me what a wider and possibly taller design might look like?

Thank you!!!

**Comment by JAG100** [comment]
I did it!!!!  Thank you so much!  

Best,
JAG100
