### ISSUE TITLE
(Kicked) You logged in from another location in #295 Build of Bungeecord

### ISSUE THREAD

**Issue by JAG100** [DrakiaXYZ/Stargate-Bukkit#12]
Just FYI - Technically speaking, not sure whether Stargate itself has an issue to resolve or if it's all Bungeecord...

Please see report at:
https://github.com/ElasticPortalSuite/BungeeCord/issues/216#issuecomment-15165039

**Comment by JAG100** [comment]
MD_5 states:

Added a friendly error instead of kick.
New versions dont support same server because they do the connection in the background.

It sounds like his proxy won't support same server connections so does that mean we'll need an update to Stargate to handle these TP requests locally and not communicate them to Bungeecord?

**Comment by md-5** [comment]
Jeez, stargate shouldn't really be sending _all_ tp requests through bungee.
This is the code I have now, prevents the kick error and lays all blame on stargate xD:

``` java
        if ( getServer() != null && getServer().getInfo() == target )
        {
            sendMessage( ChatColor.RED + "Cannot connect to server you are already on!" );
        } else
        {
            connect( target, false );
        }
```

**Comment by JAG100** [comment]
Everyone using Stargate will have serious problems the minute they upgrade to the next release build of Bungeecord which is probably any day now!!!

**Comment by JAG100** [comment]
OMG.  I think I'm just going to kill myself and be done with it.  :-)

I've always used "U" at the bottom of the gates whether it be a true server - server Bungee Gate or just a local server gate and it's always worked before.  I'm guessing if I just remove the "U" everything will be fine.  DOH!!!!

**Comment by DrakiaXYZ** [comment]
Stargate sends all Bungee gate teleports via BungeeCord, I didn't think anyone would actually do same-server bungee gates...

I'll release an update tonight to fix this.

**Comment by DrakiaXYZ** [comment]
Hmm... Just realized, I have no method of knowing whether or not the target server is this server (BungeeCord knows that, not Stargate), therefore I can't put in a fix for this...
