### ISSUE TITLE
Minecarts not working through BungeeGates

### ISSUE THREAD

**Issue by JAG100** [DrakiaXYZ/Stargate-Bukkit#14]
I upgraded today 4/26/13 to the latest Stargate version as part of my troubleshooting.  I've tried everything, including different gate sizes, and I can't seem to ride a minecart through a stargate and get teleported properly.  If I put tracks on both side of a stargate I ride right through but do not get teleported to the other server.  I thought stargate supported teleportation of players riding through on minecarts.  Is this not correct?

**Comment by DrakiaXYZ** [comment]
There is currently no method of allowing teleport of minecarts between servers. This is not a planned feature
