### ISSUE TITLE
BUNGEE GATE DOES NOT EXIST?

### ISSUE THREAD

**Issue by JAG100** [DrakiaXYZ/Stargate-Bukkit#8]
I haven't figured out what is causing the following situation to occur but at random times when players log in I see what is shown below in the logfile.  It only seems to be associated with my default server and in the Bungee config file I have bungee forcing users to log into default server upon joining.  I have a hub with multiple fixed stargates configured that take users to a variety of servers.  On many servers, there is a return portal and those are ALWAYS pointed to the main "Spawn 1" on the default server.  This way, returning players always come back to the main server through the "Spawn 1" gate.

Any ideas what could be causing this?

2013-02-23 04:17:37 [INFO] noogen1[/127.0.0.1:51326] logged in with entity id 751216 at ([world] 797.5, 163.0, 690.5)
2013-02-23 04:17:37 [INFO] [Stargate] Bungee gate spawn1 does not exist

**Comment by DrakiaXYZ** [comment]
GitHub is terrible at informing me of issues people open. Sorry about the delay in response!

My best guess, you say your primary gate is "Spawn 1" but the error is saying "spawn1" doesn't exist, could you have spelled the destination gate name wrong? (You missed a space, from the looks of it)
